### ISSUE TITLE
Bindgen for cuda_runtime_api.h

### ISSUE THREAD

**Issue by djmarcin** [coreylowman/cudarc#200]
I was looking for methods like `cudaGetDeviceProperties` from `include/cuda_runtime_api.h` but they don't seem to be present. Is there a reason for that, or is it just not done yet? I can look at adding a bindgen for it, if that's reasonable?

**Comment by coreylowman** [comment]
Yeah we only have support for the driver api, so no support for runtime api at the moment. I think supporting runtime api might look slightly different from the other APIs, because the safe runtime api would look very similar to the safe driver api.

Perhaps we only add the sys/result levels for runtime api?
